<a href="https://colab.research.google.com/github/zaidafnan-ai/ai-journey/blob/week-2/day%206%20numpy%20library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
# Create 3x3 matrix of random integers from 1 to 9
mat = np.random.randint(1, 10, (3, 3))
print("Matrix:\n", mat)

# Print diagonal
print("Diagonal:", np.diag(mat))

# Find sum of each row
print("Row Sums:", np.sum(mat, axis=1))


Matrix:
 [[6 7 4]
 [7 2 5]
 [8 6 9]]
Diagonal: [6 2 9]
Row Sums: [17 14 23]
